apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgre
spec:
  selector:
    matchLabels:
      app: postgre
  template:
    metadata:
      labels:
        app: postgre
    spec:
      containers:
      - name: postgre
        image: postgres:15.0
        ports:
        - containerPort: 5432
        env: 
        - name: POSTGRES_DB
          value: "kubenews"
        - name: POSTGRES_USER
          value: "devops"
        - name: POSTGRES_PASSWORD
          value: "Pg@1234"
---
apiVersion: v1
kind: Service
metadata:
  name: postgre
spec:
  selector:
    app: postgre
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: wesleymcarvalho/kube-news:{{TAG_VERSAO}}
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env: 
        - name: DB_DATABASE
          value: "kubenews"
        - name: DB_USERNAME
          value: "devops"
        - name: DB_PASSWORD
          value: "Pg@1234"
        - name: DB_HOST
          value: "postgre" #nome do service do banco do postgre
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name        
---
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  selector:
    app: web
  ports: 
  - port: 80
    targetPort: 8080
  type: LoadBalancer